FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copy everything first
COPY . .

# Restore
RUN dotnet restore LibrariumNormalized.sln

# Build
RUN dotnet build LibrariumNormalized.sln -c Release --no-restore

# Publish only API
RUN dotnet publish src/Librarium.Api/Librarium.Api.csproj -c Release -o /app/publish --no-build

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Librarium.Api.dll"]